"""Catálogo de documentos tributarios electrónicos del SII de Chile (DTE y BHE)."""

from __future__ import annotations

# Códigos según instructivos SII de Documentos Tributarios Electrónicos.
SII_DOCUMENT_TYPES: tuple[dict, ...] = (
	{
		"code": "33",
		"document_name": "Factura Electrónica",
		"allow_sales": 1,
		"allow_purchase": 1,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
		"is_honorarios": 0,
	},
	{
		"code": "34",
		"document_name": "Factura No Afecta o Exenta Electrónica",
		"allow_sales": 1,
		"allow_purchase": 1,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 1,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
		"is_honorarios": 0,
	},
	{
		"code": "39",
		"document_name": "Boleta Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
		"is_honorarios": 0,
	},
	{
		"code": "41",
		"document_name": "Boleta Exenta Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 1,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
		"is_honorarios": 0,
	},
	{
		"code": "43",
		"document_name": "Liquidación Factura Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
		"is_honorarios": 0,
	},
	{
		"code": "46",
		"document_name": "Factura de Compra Electrónica",
		"allow_sales": 0,
		"allow_purchase": 1,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 1,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
		"is_honorarios": 0,
	},
	{
		"code": "48",
		"document_name": "Boleta de Honorarios Electrónica",
		"allow_sales": 0,
		"allow_purchase": 1,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 1,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
		"is_honorarios": 1,
	},
	{
		"code": "52",
		"document_name": "Guía de Despacho Electrónica",
		"allow_sales": 0,
		"allow_purchase": 0,
		"allow_delivery_note": 1,
		"allow_purchase_receipt": 1,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
		"is_honorarios": 0,
	},
	{
		"code": "56",
		"document_name": "Nota de Débito Electrónica",
		"allow_sales": 1,
		"allow_purchase": 1,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 1,
		"is_export": 0,
		"is_honorarios": 0,
	},
	{
		"code": "61",
		"document_name": "Nota de Crédito Electrónica",
		"allow_sales": 1,
		"allow_purchase": 1,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 1,
		"is_debit_note": 0,
		"is_export": 0,
		"is_honorarios": 0,
	},
	{
		"code": "110",
		"document_name": "Factura de Exportación Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 1,
		"is_honorarios": 0,
	},
	{
		"code": "111",
		"document_name": "Nota de Débito de Exportación Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 1,
		"is_export": 1,
		"is_honorarios": 0,
	},
	{
		"code": "112",
		"document_name": "Nota de Crédito de Exportación Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 1,
		"is_debit_note": 0,
		"is_export": 1,
		"is_honorarios": 0,
	},
)

LEGACY_SII_DOCTYPE_MAP = {
	"Factura Afecta": "33",
	"Factura Exenta": "34",
	"Boleta Afecta": "39",
	"Boleta Exenta": "41",
	"Factura de Compra": "46",
	"Nota de Débito": "56",
	"Nota de Crédito": "61",
	"Comprobantes Pago Electrónico": "39",
}

TRANSACTION_DOCTYPES = (
	"Sales Invoice",
	"Purchase Invoice",
	"Delivery Note",
	"Purchase Receipt",
)

ALLOW_FIELD_BY_DOCTYPE = {
	"Sales Invoice": "allow_sales",
	"Purchase Invoice": "allow_purchase",
	"Delivery Note": "allow_delivery_note",
	"Purchase Receipt": "allow_purchase_receipt",
}

# TpoDocRef del nodo Referencia (instructivo de formato DTE del SII).
SII_REFERENCE_TYPES: tuple[dict, ...] = (
	{"code": "801", "reference_name": "Orden de Compra", "category": "Otro documento"},
	{"code": "802", "reference_name": "Nota de Pedido", "category": "Otro documento"},
	{"code": "803", "reference_name": "Contrato", "category": "Otro documento"},
	{"code": "804", "reference_name": "Resolución", "category": "Otro documento"},
	{"code": "805", "reference_name": "Proceso ChileCompra", "category": "Otro documento"},
	{"code": "806", "reference_name": "Ficha ChileCompra", "category": "Otro documento"},
	{"code": "807", "reference_name": "DUS", "category": "Otro documento"},
	{"code": "808", "reference_name": "B/L (Conocimiento de Embarque)", "category": "Otro documento"},
	{"code": "809", "reference_name": "AWB (Airway Bill)", "category": "Otro documento"},
	{"code": "810", "reference_name": "MIC/DTA", "category": "Otro documento"},
	{"code": "811", "reference_name": "Carta de Porte", "category": "Otro documento"},
	{
		"code": "812",
		"reference_name": "Resolución del SNA que califica Servicios de Exportación",
		"category": "Otro documento",
	},
	{"code": "813", "reference_name": "Pasaporte", "category": "Otro documento"},
	{"code": "814", "reference_name": "Certificado de Depósito Bolsa Prod. Chile", "category": "Otro documento"},
	{"code": "815", "reference_name": "Vale de Prenda Bolsa Prod. Chile", "category": "Otro documento"},
	{"code": "HES", "reference_name": "Hoja de Entrada de Servicios (ChileCompra)", "category": "Otro documento"},
	{"code": "SET", "reference_name": "Set de Pruebas", "category": "Otro documento"},
)
