"""Catálogo oficial de DTE electrónicos del SII de Chile."""

from __future__ import annotations

# Códigos según instructivos SII de Documentos Tributarios Electrónicos.
SII_DOCUMENT_TYPES: tuple[dict, ...] = (
	{
		"code": "33",
		"document_name": "Factura Electrónica",
		"allow_sales": 1,
		"allow_purchase": 1,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
	},
	{
		"code": "34",
		"document_name": "Factura No Afecta o Exenta Electrónica",
		"allow_sales": 1,
		"allow_purchase": 1,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 1,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
	},
	{
		"code": "39",
		"document_name": "Boleta Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
	},
	{
		"code": "41",
		"document_name": "Boleta Exenta Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 1,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
	},
	{
		"code": "43",
		"document_name": "Liquidación Factura Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
	},
	{
		"code": "46",
		"document_name": "Factura de Compra Electrónica",
		"allow_sales": 0,
		"allow_purchase": 1,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 1,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
	},
	{
		"code": "52",
		"document_name": "Guía de Despacho Electrónica",
		"allow_sales": 0,
		"allow_purchase": 0,
		"allow_delivery_note": 1,
		"allow_purchase_receipt": 1,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 0,
	},
	{
		"code": "56",
		"document_name": "Nota de Débito Electrónica",
		"allow_sales": 1,
		"allow_purchase": 1,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 1,
		"is_export": 0,
	},
	{
		"code": "61",
		"document_name": "Nota de Crédito Electrónica",
		"allow_sales": 1,
		"allow_purchase": 1,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 1,
		"is_debit_note": 0,
		"is_export": 0,
	},
	{
		"code": "110",
		"document_name": "Factura de Exportación Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 0,
		"is_export": 1,
	},
	{
		"code": "111",
		"document_name": "Nota de Débito de Exportación Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 0,
		"is_debit_note": 1,
		"is_export": 1,
	},
	{
		"code": "112",
		"document_name": "Nota de Crédito de Exportación Electrónica",
		"allow_sales": 1,
		"allow_purchase": 0,
		"allow_delivery_note": 0,
		"allow_purchase_receipt": 0,
		"issued_by_company": 0,
		"is_exempt": 0,
		"is_credit_note": 1,
		"is_debit_note": 0,
		"is_export": 1,
	},
)

LEGACY_SII_DOCTYPE_MAP = {
	"Factura Afecta": "33",
	"Factura Exenta": "34",
	"Boleta Afecta": "39",
	"Boleta Exenta": "41",
	"Factura de Compra": "46",
	"Nota de Débito": "56",
	"Nota de Crédito": "61",
	"Comprobantes Pago Electrónico": "39",
}

TRANSACTION_DOCTYPES = (
	"Sales Invoice",
	"Purchase Invoice",
	"Delivery Note",
	"Purchase Receipt",
)

ALLOW_FIELD_BY_DOCTYPE = {
	"Sales Invoice": "allow_sales",
	"Purchase Invoice": "allow_purchase",
	"Delivery Note": "allow_delivery_note",
	"Purchase Receipt": "allow_purchase_receipt",
}
